name: Documentation enabled
author: Jhones Bomfim

runs:
  using: 'composite'
  steps:
    - name: Check documentation
      shell: bash
      run: |
        if [ ! -f "README.md" ]; then
            echo "ERROR: README not found"
            exit 1
        fi

        line_count=$(wc -l < README.md)

        if [ $line_count -lt 3 ]; then
            echo "README file is too short, minimum 3 lines"
            exit 1
        fi

        if [ ! -f "LICENSE" ]; then
            echo "ERROR: LICENSE not found"
            exit 1
        fi

        if grep -q "]()" README.md; then
            echo "ERROR: Broken links found in README"
            exit 1
        fi

        echo "✅ Documentation checks passed"
