name: Check Merge Conflicts
author: Jhones Bomfim

runs:
  using: 'composite'
  steps:
    - name: Checking for merge conflicts...
      shell: bash
      env:
        BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
      run: |
        if [ -z "${BASE_BRANCH}" ]; then
            echo "Not a pull reuqest - skipping conflict check"
            exit 0
        fi

        git fetch origin "$BASE_BRANCH"

        if git merge --no-commit --no-ff "origin/$BASE_BRANCH" 2>&1 | tee /tmp/merge-output.txt; then
            echo "No merge conflicts detected"
            git merge --abort 2>/dev/null || true
            exit 0
        else
            if grep - "CONFLICT" /tmp/merge-output.txt; then
                echo "ERROR: Merge conflicts detected ! Please resolve"
                git merge --abort 2>/dev/null || true
                exit 0
            else
                echo "No merge conflicts found"
                git merge --abort 2>/dev/null || true
                exit 0
            fi
        fi
