name: Linting
author: Jhones Bomfim

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Sync Dependencies
      run: uv sync
      shell: bash
    - name: Run Pre-Commit
      run: uv run pre-commit run --all-files --show-diff-on-failure
      shell: bash
